%%%---------------------------------------------
%%% 文件自动生成
%%%
%%% 根据error.xml生成
%%%
%%% 请勿手动修改
%%%---------------------------------------------

%% 注册失败
-define(ERROR_1, 1).
%% 登陆密码错误
-define(ERROR_2, 2).
%% 验证错误
-define(ERROR_3, 3).
%% 登陆超时
-define(ERROR_4, 4).
%% 您的账号在其他地方登陆
-define(ERROR_5, 5).
%% 没有可用的用户数据网关节点
-define(ERROR_6, 6).
%% 数据库访问超时
-define(ERROR_7, 7).
%% 没有此账号
-define(ERROR_8, 8).
%% 账号密码错误
-define(ERROR_9, 9).
%% 数据库错误，请联系gm
-define(ERROR_10, 10).
%% 账号已存在
-define(ERROR_11, 11).
%% 登陆异常，请稍后尝试
-define(ERROR_12, 12).
%% 请稍后
-define(ERROR_13, 13).
%% 服务暂时关闭
-define(ERROR_14, 14).
%% 先登录服务
-define(ERROR_15, 15).
%% 场景登录服务异常,请重试
-define(ERROR_16, 16).
%% 事件已消失
-define(ERROR_17, 17).
%% 不在事件范围内
-define(ERROR_18, 18).
%% 事件已接
-define(ERROR_19, 19).
%% 事件正在接受中，请稍后
-define(ERROR_20, 20).
%% 事件接取失败，人数已满
-define(ERROR_21, 21).
%% 道具不存在，合成失败
-define(ERROR_22, 22).
%% 材料不足，合成失败
-define(ERROR_23, 23).
%% 类型错误，不是图纸
-define(ERROR_24, 24).
%% 事件已结束
-define(ERROR_25, 25).
%% 异常错误，请联系GM
-define(ERROR_26, 26).
%% 宠物已派遣
-define(ERROR_27, 27).
%% 派遣的不是日常事件，参数错误
-define(ERROR_28, 28).
%% 派遣的是日常事件，参数错误
-define(ERROR_29, 29).
%% 对应宠物缺少速度属性，派遣失败！
-define(ERROR_30, 30).
%% 宠物位置参数错误
-define(ERROR_31, 31).
%% 聊天cd中...
-define(ERROR_32, 32).
%% 聊天服务器异常，请稍后在做尝试...
-define(ERROR_33, 33).
%% 道具不存在，使用失败
-define(ERROR_34, 34).
%% 道具模板类型错误，使用失败
-define(ERROR_35, 35).
%% 已有该配方，使用失败
-define(ERROR_36, 36).
%% 缺少配方，合成失败
-define(ERROR_37, 37).
%% 异常错误，请联系GM
-define(ERROR_38, 38).
%% 异常错误，请联系GM
-define(ERROR_39, 39).
%% 异常错误，请联系GM
-define(ERROR_40, 40).
%% 异常错误，请联系GM
-define(ERROR_41, 41).
%% 异常错误，请联系GM
-define(ERROR_42, 42).
%% 异常错误，请联系GM
-define(ERROR_43, 43).
%% 异常错误，请联系GM
-define(ERROR_44, 44).
