{
    [
	"../*",
        "./*",
        "./*/*",
        "./*/*/*",
        "./*/*/*/*",
        "./*/*/*/*/*"
    ],
    [
        %bin_opt_info,
        %debug_info,
		{i, "../include"},
		{outdir, "../ebin"},
		inline,
        {inline_size, 30}
       %	report,
       %	{d,debug},
       	%warnings_as_errors
       %	verbose
	]
}.
